name: flutter_fixit_warehouse
description: "Firebase Flutter Fixit Warehouse Sample"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.6.8
  flutter_markdown: ^0.7.3+2
  future_builder_ex: ^5.0.0
  split_view: ^3.2.1

dev_dependencies:
  all_lint_rules_community: ^0.0.43

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
